In [1]:
import pandas as pd
import sys

sys.path.append("../src")

from skill_extractor import extract_skills
from role_classifier import classify_role

In [2]:
df = pd.read_csv("../data/sample_inputs/sample_job_descriptions.csv")
df.head()

   job_id                                    job_description
0       1  We are looking for a Data Analyst with strong ...
1       2  We are hiring a Data Scientist with experience...
2       3  Seeking a Data Engineer with expertise in ETL ...
3       4  We need a Machine Learning Engineer who can de...

In [3]:
df["extracted_skills"] = df["job_description"].apply(extract_skills)
df["predicted_role"] = df["job_description"].apply(classify_role)

df[["job_id", "predicted_role", "extracted_skills"]]

,job_id,predicted_role,extracted_skills
0,1,Data Analyst,"[dashboards, excel, power bi, sql]"
1,2,Data Scientist,"[machine learning, model development, python, ..."
2,3,Data Engineer,"[aws, cloud, etl, spark, workflow automation]"
3,4,Machine Learning Engineer,"[cloud, machine learning, python, tensorflow]"

In [4]:
from resume_advisor import generate_resume_advice

In [5]:
df["resume_advice_output"] = df.apply(
    lambda row: generate_resume_advice(
        predicted_role=row["predicted_role"],
        extracted_skills=row["extracted_skills"]
    ),
    axis=1
)

In [6]:
df["resume_advice_output"].iloc[0]

{'predicted_role': 'Data Analyst',
 'matched_skills': ['dashboards', 'excel', 'power bi', 'sql'],
 'missing_keywords': ['tableau',
  'reporting',
  'business insights',
  'stakeholder communication'],
 'resume_advice': 'Highlight dashboard building, SQL analysis, reporting, and business communication projects.'}

In [7]:
df["matched_skills"] = df["resume_advice_output"].apply(lambda x: x["matched_skills"])
df["missing_keywords"] = df["resume_advice_output"].apply(lambda x: x["missing_keywords"])
df["resume_advice"] = df["resume_advice_output"].apply(lambda x: x["resume_advice"])

df[["job_id", "predicted_role", "matched_skills", "missing_keywords", "resume_advice"]]

,job_id,predicted_role,matched_skills,missing_keywords,resume_advice
0,1,Data Analyst,"[dashboards, excel, power bi, sql]","[tableau, reporting, business insights, stakeh...","Highlight dashboard building, SQL analysis, re..."
1,2,Data Scientist,"[machine learning, model development, python, ...","[experimentation, data analysis]","Highlight machine learning projects, Python, s..."
2,3,Data Engineer,"[aws, cloud, etl, spark, workflow automation]","[data pipelines, large-scale data processing]","Highlight ETL pipelines, cloud platforms, work..."
3,4,Machine Learning Engineer,"[cloud, machine learning, python, tensorflow]","[deployment, model monitoring, production, clo...","Highlight ML deployment, Python, TensorFlow, p..."